version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ${HOME}/mongo/data:/data/db
  spring-websockets:
    image: spring-websockets
    container_name: spring-service
    ports:
      - "8080:8080"
